# Generated by Django 3.1 on 2020-08-10 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petiqrContainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=256)),
                ('cityCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('cityUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('cityCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqrContainer.countries')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=256)),
                ('stateCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('stateUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('stateCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqrContainer.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('ownerId', models.AutoField(primary_key=True, serialize=False)),
                ('ownerEmail', models.CharField(max_length=256)),
                ('ownerName', models.CharField(max_length=256)),
                ('ownerAddress', models.CharField(max_length=256)),
                ('ownerPhone', models.CharField(max_length=50)),
                ('ownerNeighborhood', models.CharField(max_length=50)),
                ('ownerPetName', models.CharField(max_length=50)),
                ('ownerPetType', models.CharField(max_length=50)),
                ('ownerCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ownerUpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ownerCityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqrContainer.cities')),
                ('ownerCountryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqrContainer.countries')),
                ('ownerStateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqrContainer.states')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='cityStateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petiqrContainer.states'),
        ),
    ]
